on: [push, pull_request]
name: Tox Multi-platform Compatibility Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        python-version: ['3.9', '3.10', '3.11']
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-2019
      fail-fast: false
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: requirements-dev.txt
      - name: Install requirements
        run: |
          pip install uv
      - name: Run tox
        run: uvx --with-requirements requirements-dev.txt tox -e py -vvv
        env:
          UV_PYTHON: ${{matrix.python-version}}
          PIP_EXTRA_INDEX_URL: ${{vars.PIP_EXTRA_INDEX_URL}}
